### ISSUE TITLE
Issue with full trajectory query

### ISSUE THREAD

**Issue by cherrera2001** [hashmapinc/Drillflow#285]
this query :

```xml
<?xml version="1.0" encoding="UTF-8"?>
<trajectorys version="1.3.1.1" xmlns="http://www.witsml.org/schemas/131">
	<documentInfo>
		<DocumentName></DocumentName>
		<FileCreationInformation>
			<FileCreationDate></FileCreationDate>
			<SoftwareName></SoftwareName>
			<FileCreator></FileCreator>
		</FileCreationInformation>
	</documentInfo>
	<trajectory uidWell="uid12333" uidWellbore="2f74b464-c789-4cfb-a508-f31e2fdd31ad" uid="950e46ec-d59b-4920-b73a-8eefb41527b1">
		<nameWell></nameWell>
		<nameWellbore></nameWellbore>
		<name></name>
		<parentTrajectory>
			<trajectory uidRef=""></trajectory>
		</parentTrajectory>
		<dTimTrajStart></dTimTrajStart>
		<dTimTrajEnd></dTimTrajEnd>
		<mdMn uom=""></mdMn>
		<mdMx uom=""></mdMx>
		<serviceCompany></serviceCompany>
		<magDeclUsed uom=""></magDeclUsed>
		<gridCorUsed uom=""></gridCorUsed>
		<aziVertSect uom=""></aziVertSect>
		<dispNsVertSectOrig uom=""></dispNsVertSectOrig>
		<dispEwVertSectOrig uom=""></dispEwVertSectOrig>
		<definitive></definitive>
		<memory></memory>
		<finalTraj></finalTraj>
		<aziRef></aziRef>
		<trajectoryStation uid="">
			<dTimStn></dTimStn>
			<typeTrajStation></typeTrajStation>
			<md uom=""></md>
			<tvd uom=""></tvd>
			<incl uom=""></incl>
			<azi uom=""></azi>
			<mtf uom=""></mtf>
			<gtf uom=""></gtf>
			<dispNs uom=""></dispNs>
			<dispEw uom=""></dispEw>
			<vertSect uom=""></vertSect>
			<dls uom=""></dls>
			<rateTurn uom=""></rateTurn>
			<rateBuild uom=""></rateBuild>
			<mdDelta uom=""></mdDelta>
			<tvdDelta uom=""></tvdDelta>
			<modelToolError></modelToolError>
			<gravTotalUncert uom=""></gravTotalUncert>
			<dipAngleUncert uom=""></dipAngleUncert>
			<magTotalUncert uom=""></magTotalUncert>
			<gravAccelCorUsed></gravAccelCorUsed>
			<magXAxialCorUsed></magXAxialCorUsed>
			<sagCorUsed></sagCorUsed>
			<magDrlstrCorUsed></magDrlstrCorUsed>
			<statusTrajStation></statusTrajStation>
			<rawData>
				<gravAxialRaw uom=""></gravAxialRaw>
				<gravTran1Raw uom=""></gravTran1Raw>
				<gravTran2Raw uom=""></gravTran2Raw>
				<magAxialRaw uom=""></magAxialRaw>
				<magTran1Raw uom=""></magTran1Raw>
				<magTran2Raw uom=""></magTran2Raw>
			</rawData>
			<corUsed>
				<gravAxialAccelCor uom=""></gravAxialAccelCor>
				<gravTran1AccelCor uom=""></gravTran1AccelCor>
				<gravTran2AccelCor uom=""></gravTran2AccelCor>
				<magAxialDrlstrCor uom=""></magAxialDrlstrCor>
				<magTran1DrlstrCor uom=""></magTran1DrlstrCor>
				<magTran2DrlstrCor uom=""></magTran2DrlstrCor>
				<sagIncCor uom=""></sagIncCor>
				<sagAziCor uom=""></sagAziCor>
				<stnMagDeclUsed uom=""></stnMagDeclUsed>
				<stnGridCorUsed uom=""></stnGridCorUsed>
				<dirSensorOffset uom=""></dirSensorOffset>
			</corUsed>
			<valid>
				<magTotalFieldCalc uom=""></magTotalFieldCalc>
				<magDipAngleCalc uom=""></magDipAngleCalc>
				<gravTotalFieldCalc uom=""></gravTotalFieldCalc>
			</valid>
			<matrixCov>
				<varianceNN uom=""></varianceNN>
				<varianceNE uom=""></varianceNE>
				<varianceNVert uom=""></varianceNVert>
				<varianceEE uom=""></varianceEE>
				<varianceEVert uom=""></varianceEVert>
				<varianceVertVert uom=""></varianceVertVert>
				<biasN uom=""></biasN>
				<biasE uom=""></biasE>
				<biasVert uom=""></biasVert>
			</matrixCov>
			<location uid="">
				<wellCRS uidRef=""></wellCRS>
				<latitude uom=""></latitude>
				<longitude uom=""></longitude>
				<easting uom=""></easting>
				<northing uom=""></northing>
				<westing uom=""></westing>
				<southing uom=""></southing>
				<projectedX uom=""></projectedX>
				<projectedY uom=""></projectedY>
				<localX uom=""></localX>
				<localY uom=""></localY>
			</location>
			<commonData>
				<dTimCreation></dTimCreation>
				<dTimLastChange></dTimLastChange>
				<itemState></itemState>
				<comments></comments>
			</commonData>
		</trajectoryStation>
		<commonData>
			<dTimCreation></dTimCreation>
			<dTimLastChange></dTimLastChange>
			<itemState></itemState>
			<comments></comments>
		</commonData>
	</trajectory>
</trajectorys>
```
results in this error:

```
java.lang.NullPointerException
	at com.hashmapinc.tempus.WitsmlObjects.v1411.WellVerticalDepthCoord.to20WellVerticalDepthCoord(WellVerticalDepthCoord.java:130)
	at com.hashmapinc.tempus.WitsmlObjects.v1411.CsTrajectoryStation.to20TrajectoryStation(CsTrajectoryStation.java:1587)
	at com.hashmapinc.tempus.WitsmlObjects.Util.TrajectoryConverter.convertTo20(TrajectoryConverter.java:287)
	at com.hashmapinc.tempus.WitsmlObjects.Util.TrajectoryConverter.convertTo20(TrajectoryConverter.java:228)
	at com.hashmapinc.tempus.WitsmlObjects.v1311.ObjTrajectory.getJSONString(ObjTrajectory.java:776)
```

**Comment by cherrera2001** [comment]
This was resolved by #288. Verified working in the latest master.
